blog/urls.py
from django.urls import path
from blog.views import *

app_name = "blog"

urlpatterns = [
    path("", blog_index, name="blog_index"),
    path("about/<int:pk>/", blog_about, name="blog_about"),
    path("category/<str:cat_name>/", blog_index, name="blog_category"),
    path("tag/<str:tag_name>/", blog_index, name="blog_tag"),
    path("author/<str:author>/", blog_index, name="blog_author"),
    path("search/", blog_search, name="blog_search"),
    path('test/', test_view, name='test_view'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from websiteApp.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from websiteApp.sitemaps import StaticViewSitemap
from blog.sitemaps import *
from debug_toolbar.toolbar import debug_toolbar_urls # type: ignore 
from django.contrib.auth import views as auth_views
from mysite.views import coming_soon



sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap
}

urlpatterns = [
    re_path(r'^.*$', coming_soon),
    path("admin/", admin.site.urls),
    path("", include("websiteApp.urls")),
    path("blog/", include("blog.urls")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path("accounts/", include('accounts.urls')),
] + debug_toolbar_urls()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websiteApp/urls.py
from django.urls import path
from websiteApp.views import *


app_name = 'websiteApp'



urlpatterns = [
    path("", home, name='index'),
    path("about/", about, name='about'),
    path("contact/", contact, name='contact'),
    path("http_test/", http_test),
    path("json_test/", json_test),
    path('newsletter/', newsletter_view, name='newsletter'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.id} - {self.name}"  # pyright: ignore[reportAttributeAccessIssue]


class Post(models.Model):
    image = models.ImageField(upload_to="blog/", default="blog/default.jpg")
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    tag = TaggableManager()
    category = models.ManyToManyField(Category)
    views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published = models.DateTimeField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return f"{self.id} - {self.title}"  # pyright: ignore[reportAttributeAccessIssue]

    def snippet(self):
        return f"{self.content[:5]}..."  # pyright: ignore

    def get_absolute_url(self):
        return reverse("blog:blog_about", kwargs={"pk": self.id})  # pyright: ignore


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    published_created = models.DateTimeField(auto_now=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blog.models import Post, Category, Comment
from django.utils import timezone
from django.http import Http404, HttpResponse, HttpResponseRedirect
from blog.form import NameForm, BlogContact
from websiteApp.form import NewsLetterForm
from .form import CommentForm
from django.contrib import messages
from django.shortcuts import redirect



# Create your views here.
def blog_index(request, cat_name=None, author=None, tag_name=None):
    posts = Post.objects.filter(status=1, published__lte=timezone.now())
    if cat_name:
        posts = posts.filter(category__name=cat_name)
    elif author:
        posts = posts.filter(author__username=author)
    elif tag_name:
        posts = posts.filter(tag__name__in=[tag_name])

    posts = Paginator(posts, 1)
    try:  
        page = int(request.GET.get('p', 1))
        posts = posts.page(page)
    except (EmptyPage, ValueError, PageNotAnInteger):
        raise Http404("Page not found")
        
    return render(request, "blog/blog_index.html",{'posts': posts})


def blog_about(request, pk):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Successful.')
            redirect(request.path)
        else:
            messages.add_message(request, messages.ERROR, 'Error encountered.')
            
    post = get_object_or_404(Post, id=pk, status=1, published__lte=timezone.now())
    # Find previous and next posts
    prev_post = Post.objects.filter(status=1, published__lte=timezone.now(), id__lt=post.id).order_by('-id').first() # type: ignore
    next_post = Post.objects.filter(status=1, published__lte=timezone.now(), id__gt=post.id).order_by('id').first() # type: ignore
    comments = Comment.objects.filter(post=post, approved=True)
    context = {
        'post': post,
        'prev_post': prev_post,
        'next_post': next_post,
        'comments': comments,
    }
    post.views += 1
    post.save(update_fields=['views'])
    return render(request, 'blog/blog_about.html', context)

def test_view(request):
    
    if request.method == 'POST':
        form = BlogContact(request.POST)
        if form.is_valid():
            form.save()        
            return HttpResponse('K200')
        else:
            print(form.errors)
     
    form = BlogContact()

    return render(request,'blog/test.html', {'form': form})



def blog_search(request):
    query = request.GET.get('s')
    posts = Post.objects.filter(status=1, published__lte=timezone.now())
    if query:
        posts = (posts.filter(title__icontains=query) | posts.filter(content__icontains=query)).distinct()
    return render(request, 'blog/blog_index.html', {'posts': posts, 'search_query': query})

templates/blog/blog_about.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load blog_tags %}

			<!-- start banner Area -->
			<section class="relative about-banner">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								Blog Details Page				
							</h1>	
							<p class="text-white link-nav"><a href="{% url 'websiteApp:index' %}">Home </a>  <span class="lnr lnr-arrow-right"></span><a href="{% url 'blog:blog_index' %}">Blog </a> <span class="lnr lnr-arrow-right"></span> <a href="blog-single.html">{{post.title}} </a> 
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->					  
			
			<!-- Start post-content Area -->
			<section class="post-content-area single-post-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							<div class="single-post row">
								<div class="col-lg-12">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image.url}}" alt="">
									</div>									
								</div>
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{% for c in post.category.all %}
										<li><a href="{% url 'blog:blog_category' c.name %}">
												{{ c.name }}{% if not forloop.last %}, {% endif %}
										</a></li>											
										{% endfor %}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:blog_author' post.author %}">{{post.author}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published|date:"D d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
									<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.views}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">Comments</a> <span class="lnr lnr-bubble"></span></p>
										<ul class="social-links col-lg-12 col-md-12 col-6">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-github"></i></a></li>
											<li><a href="#"><i class="fa fa-behance"></i></a></li>
										</ul>																				
									</div>
								</div>
								<div class="col-lg-9 col-md-9">
									<h3 class="mt-20 mb-20">{{post.title}}</h3>
									<p class="excert">
										{{post.content}}
									</p>
									<div class="row mt-30 mb-30">
										<div class="col-6">
										</div>
										<div class="col-6">
										</div>	
										<div class="col-lg-12 mt-30">
											<p>
											</p>
											<p>
											</p>											
										</div>									
									</div>
								</div>
							</div>
							<div class="navigation-area">
								<div class="row">
									<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
										{% if prev_post %}
											<div class="thumb">
												<a href="{% url 'blog:blog_about' prev_post.id %}">
													<img class="img-fluid" src="{{ prev_post.image.url }}" alt="">
												</a>
											</div>
											<div class="arrow">
												<a href="{% url 'blog:blog_about' prev_post.id %}">
													<span class="lnr text-white lnr-arrow-left"></span>
												</a>
											</div>
											<div class="detials">
												<p>Prev Post</p>
												<a href="{% url 'blog:blog_about' prev_post.id %}"><h4>{{ prev_post.title }}</h4></a>
											</div>
										{% endif %}
									</div>
									<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
										{% if next_post %}
											<div class="detials">
												<p>Next Post</p>
												<a href="{% url 'blog:blog_about' next_post.id %}"><h4>{{ next_post.title }}</h4></a>
											</div>
											<div class="arrow">
												<a href="{% url 'blog:blog_about' next_post.id %}">
													<span class="lnr text-white lnr-arrow-right"></span>
												</a>
											</div>
											<div class="thumb">
												<a href="{% url 'blog:blog_about' next_post.id %}">
													<img class="img-fluid" src="{{ next_post.image.url }}" alt="">
												</a>
											</div>
										{% endif %}
									</div>								
								</div>
							</div>
							<div class="comments-area">
								<h4>{{ comments|length }} Comment(s)</h4>
								<div class="comment-list">
									{% for comment in comments %}
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{% static 'websiteApp/img/blog/c1.jpg' %}" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">{{ comment.name }}</a></h5>
                                                <p class="date">{{ comment.created_date|date:"D d M Y" }}</p>
                                                <p class="comment">
                                                    {{ comment.message }}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
								{% endfor %}
							</div>
							<div class="comment-form">
								<h4>Leave a Comment</h4>
								<form method="post" action="">
								{% csrf_token %}
									<div class="form-group form-inline">
									  <div class="form-group col-lg-6 col-md-12 name">
										<input type="hidden" name="post" value="{{ post.id }}">
									    <input type="text" class="form-control" name="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
									  </div>
									  <div class="form-group col-lg-6 col-md-12 email">
									    <input type="email" class="form-control" name="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
									  </div>										
									</div>
									<div class="form-group">
										<input type="text" class="form-control" name="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
									</div>
									<div class="form-group">
										<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
									</div>
									<button type="submit" class="primary-btn text-uppercase">Post Comment</button>	
								</form>
							</div>
						</div>
								{% search %}
								<div class="single-sidebar-widget user-info-widget">
									<img src="{% static 'websiteApp/img/blog/user-info.png' %}" alt="">
									<a href="#"><h4>Charlie Barber</h4></a>
									<p>
										Senior blog writer
									</p>
									<ul class="social-links">
										<li><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#"><i class="fa fa-github"></i></a></li>
										<li><a href="#"><i class="fa fa-behance"></i></a></li>
									</ul>
									<p>
										Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
									</p>
								</div>
									{% popularposts %}
								<div class="single-sidebar-widget ads-widget">
									<a href="#"><img class="img-fluid" src="{% static 'websiteApp/img/blog/ads-banner.jpg' %}" alt=""></a>
								</div>
									{% categories %}
								<div class="single-sidebar-widget newsletter-widget">
									<h4 class="newsletter-title">Newsletter</h4>
									<p>
										Here, I focus on a range of items and features that we use in life without
										giving them a second thought.
									</p>
									<div class="form-group d-flex flex-row">
									   <div class="col-autos">
									      <div class="input-group">
									        <div class="input-group-prepend">
									          <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
											</div>
									        </div>
									        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
									      </div>
									    </div>
									    <a href="#" class="bbtns">Subcribe</a>
									</div>	
									<p class="text-bottom">
										You can unsubscribe at any time
									</p>								
								</div>
								{% tags %}
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
			
{% endblock %}

templates/blog/blog_index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load blog_tags %}

			<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							<h1 class="text-white">
								Dude You’re Getting
								a Telescope				
							</h1>	
							<p class="text-white">
								There is a moment in the life of any aspiring astronomer that it is time to buy that first
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">		
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'websiteApp/img/blog/cat-widget1.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
								        <span></span>								        
								        <p>Enjoy your social life together</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'websiteApp/img/blog/cat-widget2.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
								        <span></span>								        
								        <p>Be a part of politics</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'websiteApp/img/blog/cat-widget3.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Food</h4>
								        <span></span>
								        <p>Let the food be finished</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>												
					</div>
				</div>	
			</section>
			<!-- End top-category-widget Area -->
			
			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							{% for post in posts %}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										<li><a href="#">
										{% for c in post.category.all %}
											<li><a href="{% url 'blog:blog_category' c.name %}">
													{{ c.name }}{% if not forloop.last %}, {% endif %}
											</a></li>
										{% endfor %}

									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:blog_author' post.author %}">{{post.author}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ post.published|date:"D d M Y" }}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.views}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">post_comments</a> <span class="lnr lnr-bubble"></span></p>						
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{ post.image.url }}" alt="">
									</div>
									<a class="posts-title" href="{% url 'blog:blog_about' post.id %}"><h3>{{post.title}}</h3></a>
									<p class="excert">
										{{post.content|truncatewords:3}}
									</p>
									<a href="{% url 'blog:blog_about' post.id %}" class="primary-btn">View More</a>
								</div>
							</div>{% endfor %}

		                    <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
		                            <li class="page-item">
										{% if posts.has_previous %}
		                                <a href="?p={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
										{% endif %}
		                            </li>
									{% for num in posts.paginator.page_range %}
										{% if posts.number == num %}
											<li class="page-item active"><a href="?p={{ num }}" class="page-link">{{ num }}</a></li>
										{% else %}
											<li class="page-item"><a href="?p={{ num }}" class="page-link	">{{ num }}</a></li>
										{% endif %}
									{% endfor %}
		    
										{% if posts.has_next %}
		                                <a href="?p={{ posts.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
										{% endif %}
		                            </li>
		                        </ul>
		                    </nav>
						</div>
								{% search %}
								<div class="single-sidebar-widget user-info-widget">
									<img src="{% static 'websiteApp/img/blog/user-info.png' %}" alt="">
									<a href="#"><h4>Charlie Barber</h4></a>
									<p>
										Senior blog writer
									</p>
									<ul class="social-links">
										<li><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li><a href="#"><i class="fa fa-github"></i></a></li>
										<li><a href="#"><i class="fa fa-behance"></i></a></li>
									</ul>
									<p>
										Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
									</p>
								</div>
									{% popularposts %}
								<div class="single-sidebar-widget ads-widget">
									<a href="#"><img class="img-fluid" src="{% static 'websiteApp/img/blog/ads-banner.jpg' %}" alt=""></a>
								</div>
									{% categories %}
								<div class="single-sidebar-widget newsletter-widget">
									<h4 class="newsletter-title">Newsletter</h4>
									<p>
										Here, I focus on a range of items and features that we use in life without
										giving them a second thought.
									</p>
									<div class="form-group d-flex flex-row">
									   <div class="col-autos">
									      <div class="input-group">
									        <div class="input-group-prepend">
									          <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
											</div>
									        </div>
									        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
									      </div>
									    </div>
									    <a href="#" class="bbtns">Subcribe</a>
									</div>	
									<p class="text-bottom">
										You can unsubscribe at any time
									</p>								
								</div>
								{% tags %}							
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
{% endblock %}

templates/blog/categories.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Categories</h4>
    <ul class="cat-list">
        {% for name,count in categories.items %}
        <li>
            <a href="{% url 'blog:blog_category' name.name %}" class="d-flex justify-content-between">
                <p>{{name}} </p>
                <p>{{count}}</p>
            </a>
        </li>	
        {% endfor %}														
    </ul>
</div>

templates/blog/popularposts.html
{% load humanize %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Popular Posts</h4>
    <div class="popular-post-list">
        {% for post in posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{{ post.image.url }}">
            </div>
            <div class="details">
                <a href="{% url 'blog:blog_about' post.id %}"><h6>{{ post.title }}</h6></a>
                <p>{{ post.published|naturaltime }} - {{post.views}} views </p>
                <p> </p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/blog/search.html
<div class="col-lg-4 sidebar-widgets">
    <div class="widget-wrap">
        <div class="single-sidebar-widget search-widget">
            <form class="search-form" action="{% url 'blog:blog_search' %}" method="get">
                <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
                <button type="submit"><i class="fa fa-search"></i></button>
            </form>
        </div>

templates/blog/tags.html
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        {% for tag in tags %}
        <li><a href="{% url 'blog:blog_tag' tag.name %}">{{ tag.name }}</a></li>
        {% endfor %}
    </ul>
</div>

templates/blog/test.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title></Form:post></title>
</head>
<body>
      <form method="post">

            {% csrf_token %}
            
            {{ form.as_p }}
            
            <button type='submit'>submit</button>
      </from>
</body>
</html>